Models/FileDirectory.cs
using System.ComponentModel.DataAnnotations;

namespace HierarchicalStructureOfDirectories.Models
{
    public class FileDirectory
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]
        public string? DirectoryName { get; set; }
    }
}

Models/ParentDirectoryData.cs
namespace HierarchicalStructureOfDirectories.Models
{
    public class ParentDirectoryData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<FileDirectory> ChildsDirecories { get; set; }
    }
}

Models/RelationshipBetweenFileDirection.cs
using System.ComponentModel.DataAnnotations;

namespace HierarchicalStructureOfDirectories.Models
{
    public class RelationshipBetweenFileDirection
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]
        public int DirectoryParentId { get; set; }
        [Required]
        public int DirectoryChildId { get; set; }

    }
}

Controllers/FileDirectoryController.cs
using HierarchicalStructureOfDirectories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using HierarchicalStructureOfDirectories.Data;

namespace HierarchicalStructureOfDirectories.Controllers
{
	public class FileDirectoryController : Controller
	{
		private readonly IRelationshipBetweenDirectyRepository _relationshipRepository;
		private readonly IFileDirectoryRepository _directoryRepository;
		DirectoriesSave directoriesSave;

		public FileDirectoryController(IRelationshipBetweenDirectyRepository relationshipRepository, IFileDirectoryRepository directoryRepository)
		{
			_relationshipRepository = relationshipRepository;
			_directoryRepository = directoryRepository;
			directoriesSave = new DirectoriesSave();
		}

		public async Task<ActionResult> Index(int id = 0)
		{
			if (id == 0)
			{
				var directory = await _directoryRepository.GetFirstFIleDirectory();
				id = directory.Id;
			}

			ViewData["directories"] = await _relationshipRepository.GetRelationshipBetweenFileDirections(id);
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Upload(string sDir)
		{
			await _relationshipRepository.ClearTable();
			await _directoryRepository.ClearTable();
			await directoriesSave.SaveDirecoryToDB(sDir, _relationshipRepository, _directoryRepository);

			return RedirectToAction("Index");
		}
	}
}

Views/FileDirectory/Index.cshtml
@{
	ViewData["Title"] = "Folder";
}

@{
	ParentDirectoryData directions = ViewData["directories"] as ParentDirectoryData;

	if (directions != null)
	{
		<div style="text-align:left">
			<h4>"Folder" - @directions.Name</h4>

			<ul style="list-style-type:none">
				@foreach (var direction in directions.ChildsDirecories)
				{
					<li><a href="@Url.Action("Index", "FileDirectory", new {direction.Id})">@direction.DirectoryName</a></li>
				}
			</ul>
		</div>
	}
	else
	{
		<div style="text-align:center">
		<h4>Виникла проблема з базою данних</h4>
		</div>
	}



	@using (Html.BeginForm("Upload", "FileDirectory", FormMethod.Post))
	{
		<tr>
			<td><p>Вкажіть шлях до папки (Наприклад: D:\\Folder\\SomeFolder):</p></td>
			<td><input type="text" name="sDir" /> </td>
		</tr>
		<input type="submit" value="Відправити" />
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HierarchicalStructureOfDirectories</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HierarchicalStructureOfDirectories.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3" style="padding-top:10px;">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>